apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: fibono-xyz-tls
spec:
  secretName: fibono-xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: fibono.xyz
  dnsNames:
    - fibono.xyz
    - www.fibono.xyz
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - fibono.xyz
          - www.fibono.xyz
